Sync

diff --git a/gen-protobuf b/gen-protobuf
--- a/gen-protobuf
+++ b/gen-protobuf
@@ -7,22 +7,36 @@
 ##     exit 1
 ## fi
 
+## With protobuf, the compiler generates a single file with
+## nested static classes in it.
+## This is easier to clean up afterwards.
+
 PROTO="${1:-binary-rdf.proto}"
 
-# Find the namespace
+# Package directory
 PKG=src/main/java/
-PKG="$PKG/org/apache/jena/riot/protobuf/"
-rm -f "$PKG"/*.java
+PKG="$PKG/org/apache/jena/riot/protobuf/wire"
+OUTPUT="$PKG/PB_RDF.java"
 
+# Delete the current genrated code.
+rm -f "$OUTPUT"
+
+# Generate
 protoc --proto_path=src/main/proto/ \
        --java_out=src/main/java/ \
        src/main/proto/"$PROTO"
 
-F=$PKG/PB_RDF.java
+# Output
 
-if [ -e "$F" ]
+if [ -e "$OUTPUT" ]
 then
+    # Clean up.
     perl -i -p -e \
 	 's/^public final class/\@SuppressWarnings("all")\npublic final class/' \
-	 $F
+	 "$OUTPUT"
+    # License
+    
+else
+    echo "No output" 2>&1
+    exit 1
 fi
